#容器启动端口
server:
  port: 9090
# 数据库连接池配置,默认数据库连接池为HikariPool
spring:
  datasource:
    url: jdbc:mysql://192.168.1.190:3306/user
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 3

# 日志配置
logging:
  file: ./logs/user.log
  level:
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
  pattern: dateformat=yyyy-MM-dd HH:mm:ss